### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by MiguelMachado-dev** [forjadev/gun-organization#9]
![Image](https://user-images.githubusercontent.com/29252011/256682971-3dabad8f-0660-4187-8fdb-758b253b52ea.png)

- Create a postgresql database
- Should use docker

https://docs.railway.app/databases/postgresql

**Comment by ghost** [comment]
The diagram can be found at [this link](https://dbdiagram.io/d/64c41ff702bd1c4a5ee1ce8c). Also, here's an image: 

![Image](https://github.com/forjadev/gun-organization/assets/41487169/dad9cf6a-f918-4040-9dba-d6c8a9081630)

The column names are equivalent to the webhook fields, except for the "role" column: since we provide that information, this column equals to "Software Engineer" by default, and can be modified later.

**Comment by ghost** [comment]
We've created a `docker-compose.yml` file so that our database can be easily created and used for development purposes. For now, it looks something like this:

```yaml
services:
  database:
    hostname: database
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - "./db/gun-org.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/seed.sql:/docker-entrypoint-initdb.d/2.sql"
    ports:
      - 7772:5432
    environment:
      POSTGRES_PASSWORD: forjadev
      POSTGRES_USER: forja
      POSTGRES_DB: gun-organization-db
volumes:
  db:
```
We chose a random port (7772) on the host side because the user could already have Postgres installed on his machine. Also, we created initialization scripts that structures and populates the database with real data (`gun-org.sql` and `seed.sql`) when the container starts:

`gun-org.sql`
```sql
CREATE TABLE "users" (
  "id" integer PRIMARY KEY,
  "login" varchar,
  "html_url" varchar,
  "role" varchar,
  "team_id" integer
);

CREATE TABLE "teams" (
  "team_id" integer PRIMARY KEY,
  "name" varchar
);

ALTER TABLE "users" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("team_id");
```
`seed.sql`
```sql
insert into teams(team_id, name) values (1, 'Gungnir');
insert into teams(team_id, name) values (2, 'Mjollnir');

insert into users (id, login, html_url, role, team_id) values (1, 'andersonnaz', 'https://github.com/andersonnaz', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (2, 'tiburciohugo', 'https://github.com/tiburciohugo', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (3, 'laracarvalho', 'https://github.com/laracarvalho', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (4, 'vinirossado', 'https://github.com/vinirossado', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (5, 'danielbrazrocha', 'https://github.com/danielbrazrocha', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (6, 'walber-vaz', 'https://github.com/walber-vaz', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (7, 'MiguelMachado-dev', 'https://github.com/MiguelMachado-dev', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (8, 'Paulo-Eduardo', 'https://github.com/Paulo-Eduardo', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (9, 'rodrigofmeneses', 'https://github.com/rodrigofmeneses', 'Software Engineer', 1);
insert into users (id, login, html_url, role, team_id) values (10, 'Sevlak', 'https://github.com/Sevlak', 'Software Engineer', 1);
...
```
@MiguelMachado-dev are we proceeding correctly on the initialization scripts?
